### ISSUE TITLE
translate the readme to english 

### ISSUE THREAD

**Issue by guivictorr** [guivictorr/whatsapp-bot#28]
Create an English version of the README and include a link to it in the Portuguese (Brazil) README.

**Comment by Bolaji06** [comment]
Hello @guivictorr I can actually work on this if you let me.

**Comment by guivictorr** [comment]
> Hello @guivictorr I can actually work on this if you let me.

ok, I assigned you

**Comment by guivictorr** [comment]
closed by #30
